### ISSUE TITLE
RP2350 support

### ISSUE THREAD

**Issue by nyh-workshop** [marcel-licence/esp32_fm_synth#13]
Hello Marcel Licence,
Since the RP2350 is there, and with the FPU, could it be possible to also include this in the library? 😄

**Comment by marcel-licence** [comment]
Hello,
yes, I've started prepare the FM module within the ML_SynthTools. https://github.com/marcel-licence/ml_synth_fm_example is coming soon and will rehplace the esp32_fm_synth. It would be the same but for multiple platforms.

**Comment by marcel-licence** [comment]
I committed the initial implementation: https://github.com/marcel-licence/ml_synth_fm_example
Please let me know if you are facing issues 
here: https://github.com/marcel-licence/ml_synth_fm_example/issues
or here: https://github.com/marcel-licence/ML_SynthTools/issues
