### ISSUE TITLE
Audio Kit v. 2.3

### ISSUE THREAD

**Issue by KeenVox** [marcel-licence/esp32_fm_synth#4]
Hi,

would it work with the 2.3 version of the audio kit, which has an ES8388 chipset?

**Comment by marcel-licence** [comment]
I've never seen the Audio Kit v2.3. I have the v2.2 but the ESP32 A1S with an ES8388. 
I've merged the code from the sampler project into this one. Now it can be used with the ES8388. I've tested it some minutes ago

**Comment by KeenVox** [comment]
Nice, thx. 
 I don't know., I looked for the audio kit on german ebay and the only seller wrote 2.3. On aliexpress all kits use ES8388, so I assumed the version change = the chip change

**Comment by marcel-licence** [comment]
Maybe they've updated the Audio Kit also. That would mean there is the Audio Kit v2.2 with ESP32 A1S with AC101 or ES8388.
And finally there is also the Audio Kit v2.3 with es ESP32 A1S with ESS8388. The version of the Audio Kit is written on the PCB. The difference of the ESP32 A1S seems only detectable by the different kinds of antennas.

**Comment by marcel-licence** [comment]
I think this has been solved with the last update
