### ISSUE TITLE
ml_scope.h: No such file or directory

### ISSUE THREAD

**Issue by michaeltex** [marcel-licence/esp32_fm_synth#8]
hi!
What  a header ml_scope.h?
ML_SynthTools  not contain this file.
Where can I get it or is it not needed?
Healp please🙏

**Comment by marcel-licence** [comment]
Hi,
this is a new feature which is not avaible yet. The file is not needed.
I've updated the project. Thank you for your feedback.

**Comment by michaeltex** [comment]
thanks🙏
